name: Deploy LMS Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-lms-backend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Ensure target dir
        run: |
          ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /var/www/lms-backend/src"

      - name: Upload sources (rsync)
        run: |
          rsync -az --delete \
            --exclude '.git' --exclude '.github' --exclude 'node_modules' \
            -e "ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/lms-backend/src/

      - name: Install & restart (PM2)
        run: |
          ssh -i key.pem -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
              set -e
              cd /var/www/lms-backend/src
              npm ci
              # если TypeScript:
              # npm run build
              # и в /var/www/ecosystem.config.js поставь args: "node dist/index.js"
              cd /var/www
              pm2 startOrReload ecosystem.config.js --only lms-backend || pm2 startOrReload ecosystem.config.js
              pm2 save
            '

